package org.usfirst.frc.team159.robot;

public interface PhysicalConstants {
    double ROBOT_WIDTH = 34.25;
    double ROBOT_LENGTH = 38.5;

    double FIELD_WIDTH = 324;
    double FIELD_LENGTH = 648;

    double PORTAL_WALL_OFFSET = 29.7;
    double ROBOT_TO_SIDE = PORTAL_WALL_OFFSET + (ROBOT_WIDTH / 2);
    double ROBOT_Y_OFFSET_FROM_CENTER = 12;

    double SWITCH_LENGTH = 153.5;
    double SWITCH_WIDTH = 56;
    double SCALE_WIDTH = 50;
    double SWITCH_CENTER_FROM_WALL = 168;
    double SWITCH_EDGE_FROM_WALL = 140;
    double SWITCH_CENTER_TO_PLATE_EDGE = 58.75;
    double SWITCH_EDGE_TO_SIDE_WALL = 85.25;
    double SWITCH_HOOK_Y_DISTANCE = SWITCH_EDGE_TO_SIDE_WALL - ROBOT_TO_SIDE;

    double SCALE_PLATE_TO_SIDE_WALL = 71.57;
    double SCALE_PLATE_TO_WALL = 299.65;
    double SCALE_HOOK_Y_DISTANCE = SCALE_PLATE_TO_SIDE_WALL - ROBOT_TO_SIDE;

    double EDGE_OF_NULL_ZONE_TO_SCALE_PLATE_EDGE = 24.125;
    double NULL_ZONE_EDGE_TO_WALL = SCALE_PLATE_TO_WALL - EDGE_OF_NULL_ZONE_TO_SCALE_PLATE_EDGE;

    double ROBOT_TO_SCALE_CENTER = SCALE_PLATE_TO_WALL - ROBOT_LENGTH + (SCALE_WIDTH / 2);
    double ROBOT_TO_SWITCH = SWITCH_EDGE_FROM_WALL - ROBOT_LENGTH;
    double ROBOT_TO_SWITCH_CENTER = ROBOT_TO_SWITCH + (SWITCH_WIDTH / 2);
    double ROBOT_CENTER_X_TURN_POINT = ROBOT_TO_SWITCH / 2;
    double ROBOT_CENTER_Y_TURN_POINT = SWITCH_CENTER_TO_PLATE_EDGE / 2;
    double ROBOT_TO_SCALE_X = SCALE_PLATE_TO_WALL - ROBOT_LENGTH;

    double HOOK_Y_DISTANCE = SWITCH_EDGE_TO_SIDE_WALL - PORTAL_WALL_OFFSET - (ROBOT_WIDTH / 2);
    double SWITCH_HOOK_TURN_X = ROBOT_TO_SWITCH_CENTER - ROBOT_LENGTH;
    double SWITCH_HOOK_TURN_Y = HOOK_Y_DISTANCE / 2;
    double SCALE_HOOK_TURN_X = ROBOT_TO_SCALE_CENTER - ROBOT_LENGTH;
    double SCALE_HOOK_TURN_Y = SCALE_PLATE_TO_SIDE_WALL - PORTAL_WALL_OFFSET - (ROBOT_WIDTH / 2);
    
    double SWITCH_DROP_HEIGHT = 30; // outer encoder: actual ht=ht*2
    double SCALE_DROP_HEIGHT = 70; //

}
