package org.usfirst.frc.team159.robot;

public interface PhysicalConstants {
	double ROBOT_WIDTH = 34.25;
	double ROBOT_LENGTH = 38.5;
	
	double FIELD_WIDTH = 324;
	double FIELD_LENGTH = 648;
	
	double PORTAL_WALL_LENGTH = 36;
	
	double SWITCH_LENGTH = 153.5;
	double SWITCH_WIDTH = 56;
	
	double SWITCH_CENTER_FROM_WALL = 168;
	double SWITCH_EDGE_FROM_WALL = 140;
	double SWITCH_CENTER_TO_PLATE_EDGE = 58.75;
	double SWITCH_EDGE_TO_SIDE_WALL = 85.25;
	double ROBOT_TO_SWITCH = SWITCH_EDGE_FROM_WALL - ROBOT_LENGTH;
	double ROBOT_TO_SWITCH_CENTER = ROBOT_TO_SWITCH + (SWITCH_WIDTH/2);
	double ROBOT_CENTER_X_TURN_POINT = ROBOT_TO_SWITCH/2;
	double ROBOT_CENTER_Y_TURN_POINT = SWITCH_CENTER_TO_PLATE_EDGE/2;
	double HOOK_Y_DISTANCE = SWITCH_EDGE_TO_SIDE_WALL - PORTAL_WALL_LENGTH - (ROBOT_WIDTH/2);
	double SWITCH_HOOK_TURN_X = ROBOT_TO_SWITCH_CENTER - ROBOT_LENGTH;
	double SWITCH_HOOK_TURN_Y = HOOK_Y_DISTANCE/2;
}
